// SPDX-License-Identifier: GPL-2.0
/*
 * GENERATED by kpm/gen-shim.py -- do not edit by hand.
 *
 * A definition for every kernel function the engine references, each one a
 * tail-call through nm_kpm_sym[]. See gen-shim.py for why these are
 * trampolines and not macros -- in short, a macro cannot reach the calls
 * that kernel-header inlines make on the engine's behalf.
 *
 * Compiled against the kernel headers only for the enum; it uses no kernel
 * types and no prototypes, which is the point.
 */
#include "nm_kpm_syms.h"

/* x16 is the intra-procedure-call scratch register: free to clobber in a
 * trampoline, and argument registers are left exactly as the caller set
 * them. `br` is used rather than `bl` because it has no range limit -- the
 * +/-128 MB reach of a direct call is precisely what rules out calling the
 * kernel from a .kpm at all. */
#define NM_TRAMP(name, idx)					\
	asm(".globl " #name "\n"				\
	    ".type " #name ", %function\n"			\
	    #name ":\n"					\
	    "  adrp x16, nm_kpm_sym\n"				\
	    "  add  x16, x16, :lo12:nm_kpm_sym\n"		\
	    "  ldr  x16, [x16, #(8*" #idx ")]\n"			\
	    "  br   x16\n")

/* The asm above cannot see the enum, so the index is written as a literal.
 * These assertions are what keep the two in step: change the symbol list
 * and regenerate, or the build stops here rather than dispatching through
 * the wrong table slot at runtime. */
_Static_assert(NMS___alloc_skb == 0, "table index drift: __alloc_skb");
_Static_assert(NMS___kmalloc == 1, "table index drift: __kmalloc");
_Static_assert(NMS___list_add_valid == 2, "table index drift: __list_add_valid");
_Static_assert(NMS___list_add_valid_or_report == 3, "table index drift: __list_add_valid_or_report");
_Static_assert(NMS___list_del_entry_valid == 4, "table index drift: __list_del_entry_valid");
_Static_assert(NMS___list_del_entry_valid_or_report == 5, "table index drift: __list_del_entry_valid_or_report");
_Static_assert(NMS___netlink_dump_start == 6, "table index drift: __netlink_dump_start");
_Static_assert(NMS___netlink_kernel_create == 7, "table index drift: __netlink_kernel_create");
_Static_assert(NMS___nla_parse == 8, "table index drift: __nla_parse");
_Static_assert(NMS___nlmsg_put == 9, "table index drift: __nlmsg_put");
_Static_assert(NMS___put_cred == 10, "table index drift: __put_cred");
_Static_assert(NMS___rcu_read_lock == 11, "table index drift: __rcu_read_lock");
_Static_assert(NMS___rcu_read_unlock == 12, "table index drift: __rcu_read_unlock");
_Static_assert(NMS___warn_printk == 13, "table index drift: __warn_printk");
_Static_assert(NMS__printk == 14, "table index drift: _printk");
_Static_assert(NMS__raw_spin_lock == 15, "table index drift: _raw_spin_lock");
_Static_assert(NMS__raw_spin_lock_irqsave == 16, "table index drift: _raw_spin_lock_irqsave");
_Static_assert(NMS__raw_spin_unlock == 17, "table index drift: _raw_spin_unlock");
_Static_assert(NMS__raw_spin_unlock_irqrestore == 18, "table index drift: _raw_spin_unlock_irqrestore");
_Static_assert(NMS_bcmp == 19, "table index drift: bcmp");
_Static_assert(NMS_call_rcu == 20, "table index drift: call_rcu");
_Static_assert(NMS_clear_inode == 21, "table index drift: clear_inode");
_Static_assert(NMS_d_add == 22, "table index drift: d_add");
_Static_assert(NMS_d_drop == 23, "table index drift: d_drop");
_Static_assert(NMS_d_lookup == 24, "table index drift: d_lookup");
_Static_assert(NMS_d_splice_alias == 25, "table index drift: d_splice_alias");
_Static_assert(NMS_dentry_open == 26, "table index drift: dentry_open");
_Static_assert(NMS_do_trace_netlink_extack == 27, "table index drift: do_trace_netlink_extack");
_Static_assert(NMS_down_write == 28, "table index drift: down_write");
_Static_assert(NMS_dput == 29, "table index drift: dput");
_Static_assert(NMS_fortify_panic == 30, "table index drift: fortify_panic");
_Static_assert(NMS_fput == 31, "table index drift: fput");
_Static_assert(NMS_free_inode_nonrcu == 32, "table index drift: free_inode_nonrcu");
_Static_assert(NMS_full_name_hash == 33, "table index drift: full_name_hash");
_Static_assert(NMS_generic_file_readonly_mmap == 34, "table index drift: generic_file_readonly_mmap");
_Static_assert(NMS_generic_fillattr == 35, "table index drift: generic_fillattr");
_Static_assert(NMS_generic_permission == 36, "table index drift: generic_permission");
_Static_assert(NMS_generic_read_dir == 37, "table index drift: generic_read_dir");
_Static_assert(NMS_idr_alloc == 40, "table index drift: idr_alloc");
_Static_assert(NMS_idr_destroy == 41, "table index drift: idr_destroy");
_Static_assert(NMS_idr_find == 42, "table index drift: idr_find");
_Static_assert(NMS_idr_get_next == 43, "table index drift: idr_get_next");
_Static_assert(NMS_idr_preload == 44, "table index drift: idr_preload");
_Static_assert(NMS_idr_remove == 45, "table index drift: idr_remove");
_Static_assert(NMS_igrab == 46, "table index drift: igrab");
_Static_assert(NMS_iput == 48, "table index drift: iput");
_Static_assert(NMS_iterate_dir == 49, "table index drift: iterate_dir");
_Static_assert(NMS_kasprintf == 50, "table index drift: kasprintf");
_Static_assert(NMS_kern_path == 51, "table index drift: kern_path");
_Static_assert(NMS_kfree == 52, "table index drift: kfree");
_Static_assert(NMS_kfree_skb == 53, "table index drift: kfree_skb");
_Static_assert(NMS_kfree_skb_reason == 54, "table index drift: kfree_skb_reason");
_Static_assert(NMS_kmem_cache_alloc == 55, "table index drift: kmem_cache_alloc");
_Static_assert(NMS_kmem_cache_create == 56, "table index drift: kmem_cache_create");
_Static_assert(NMS_kmem_cache_destroy == 57, "table index drift: kmem_cache_destroy");
_Static_assert(NMS_kmem_cache_free == 58, "table index drift: kmem_cache_free");
_Static_assert(NMS_kstrdup == 59, "table index drift: kstrdup");
_Static_assert(NMS_kstrndup == 60, "table index drift: kstrndup");
_Static_assert(NMS_kvfree_call_rcu == 61, "table index drift: kvfree_call_rcu");
_Static_assert(NMS_lookup_one_len_unlocked == 62, "table index drift: lookup_one_len_unlocked");
_Static_assert(NMS_mutex_lock == 63, "table index drift: mutex_lock");
_Static_assert(NMS_mutex_unlock == 64, "table index drift: mutex_unlock");
_Static_assert(NMS_netlink_capable == 65, "table index drift: netlink_capable");
_Static_assert(NMS_netlink_kernel_release == 66, "table index drift: netlink_kernel_release");
_Static_assert(NMS_netlink_rcv_skb == 67, "table index drift: netlink_rcv_skb");
_Static_assert(NMS_netlink_unicast == 68, "table index drift: netlink_unicast");
_Static_assert(NMS_new_inode == 69, "table index drift: new_inode");
_Static_assert(NMS_nla_put == 70, "table index drift: nla_put");
_Static_assert(NMS_notify_change == 71, "table index drift: notify_change");
_Static_assert(NMS_override_creds == 72, "table index drift: override_creds");
_Static_assert(NMS_path_get == 73, "table index drift: path_get");
_Static_assert(NMS_path_put == 74, "table index drift: path_put");
_Static_assert(NMS_preempt_schedule == 75, "table index drift: preempt_schedule");
_Static_assert(NMS_prepare_creds == 76, "table index drift: prepare_creds");
_Static_assert(NMS_radix_tree_tagged == 77, "table index drift: radix_tree_tagged");
_Static_assert(NMS_rcu_barrier == 78, "table index drift: rcu_barrier");
_Static_assert(NMS_revert_creds == 79, "table index drift: revert_creds");
_Static_assert(NMS_security_inode_getsecctx == 80, "table index drift: security_inode_getsecctx");
_Static_assert(NMS_security_inode_notifysecctx == 81, "table index drift: security_inode_notifysecctx");
_Static_assert(NMS_security_release_secctx == 82, "table index drift: security_release_secctx");
_Static_assert(NMS_set_nlink == 83, "table index drift: set_nlink");
_Static_assert(NMS_shrink_dcache_sb == 84, "table index drift: shrink_dcache_sb");
_Static_assert(NMS_skb_trim == 85, "table index drift: skb_trim");
_Static_assert(NMS_sort == 86, "table index drift: sort");
_Static_assert(NMS_static_key_disable == 87, "table index drift: static_key_disable");
_Static_assert(NMS_static_key_enable == 88, "table index drift: static_key_enable");
_Static_assert(NMS_synchronize_rcu == 89, "table index drift: synchronize_rcu");
_Static_assert(NMS_truncate_inode_pages_final == 90, "table index drift: truncate_inode_pages_final");
_Static_assert(NMS_up_write == 91, "table index drift: up_write");
_Static_assert(NMS_vfs_getattr_nosec == 92, "table index drift: vfs_getattr_nosec");
_Static_assert(NMS_vfs_getxattr == 93, "table index drift: vfs_getxattr");
_Static_assert(NMS_vfs_llseek == 94, "table index drift: vfs_llseek");
_Static_assert(NMS_vfs_setxattr == 95, "table index drift: vfs_setxattr");

NM_TRAMP(__alloc_skb, 0);
NM_TRAMP(__kmalloc, 1);
NM_TRAMP(__list_add_valid, 2);
NM_TRAMP(__list_add_valid_or_report, 3);
NM_TRAMP(__list_del_entry_valid, 4);
NM_TRAMP(__list_del_entry_valid_or_report, 5);
NM_TRAMP(__netlink_dump_start, 6);
NM_TRAMP(__netlink_kernel_create, 7);
NM_TRAMP(__nla_parse, 8);
NM_TRAMP(__nlmsg_put, 9);
NM_TRAMP(__put_cred, 10);
NM_TRAMP(__rcu_read_lock, 11);
NM_TRAMP(__rcu_read_unlock, 12);
NM_TRAMP(__warn_printk, 13);
NM_TRAMP(_printk, 14);
NM_TRAMP(_raw_spin_lock, 15);
NM_TRAMP(_raw_spin_lock_irqsave, 16);
NM_TRAMP(_raw_spin_unlock, 17);
NM_TRAMP(_raw_spin_unlock_irqrestore, 18);
NM_TRAMP(bcmp, 19);
NM_TRAMP(call_rcu, 20);
NM_TRAMP(clear_inode, 21);
NM_TRAMP(d_add, 22);
NM_TRAMP(d_drop, 23);
NM_TRAMP(d_lookup, 24);
NM_TRAMP(d_splice_alias, 25);
NM_TRAMP(dentry_open, 26);
NM_TRAMP(do_trace_netlink_extack, 27);
NM_TRAMP(down_write, 28);
NM_TRAMP(dput, 29);
NM_TRAMP(fortify_panic, 30);
NM_TRAMP(fput, 31);
NM_TRAMP(free_inode_nonrcu, 32);
NM_TRAMP(full_name_hash, 33);
NM_TRAMP(generic_file_readonly_mmap, 34);
NM_TRAMP(generic_fillattr, 35);
NM_TRAMP(generic_permission, 36);
NM_TRAMP(generic_read_dir, 37);
NM_TRAMP(idr_alloc, 40);
NM_TRAMP(idr_destroy, 41);
NM_TRAMP(idr_find, 42);
NM_TRAMP(idr_get_next, 43);
NM_TRAMP(idr_preload, 44);
NM_TRAMP(idr_remove, 45);
NM_TRAMP(igrab, 46);
NM_TRAMP(iput, 48);
NM_TRAMP(iterate_dir, 49);
NM_TRAMP(kasprintf, 50);
NM_TRAMP(kern_path, 51);
NM_TRAMP(kfree, 52);
NM_TRAMP(kfree_skb, 53);
NM_TRAMP(kfree_skb_reason, 54);
NM_TRAMP(kmem_cache_alloc, 55);
NM_TRAMP(kmem_cache_create, 56);
NM_TRAMP(kmem_cache_destroy, 57);
NM_TRAMP(kmem_cache_free, 58);
NM_TRAMP(kstrdup, 59);
NM_TRAMP(kstrndup, 60);
NM_TRAMP(kvfree_call_rcu, 61);
NM_TRAMP(lookup_one_len_unlocked, 62);
NM_TRAMP(mutex_lock, 63);
NM_TRAMP(mutex_unlock, 64);
NM_TRAMP(netlink_capable, 65);
NM_TRAMP(netlink_kernel_release, 66);
NM_TRAMP(netlink_rcv_skb, 67);
NM_TRAMP(netlink_unicast, 68);
NM_TRAMP(new_inode, 69);
NM_TRAMP(nla_put, 70);
NM_TRAMP(notify_change, 71);
NM_TRAMP(override_creds, 72);
NM_TRAMP(path_get, 73);
NM_TRAMP(path_put, 74);
NM_TRAMP(preempt_schedule, 75);
NM_TRAMP(prepare_creds, 76);
NM_TRAMP(radix_tree_tagged, 77);
NM_TRAMP(rcu_barrier, 78);
NM_TRAMP(revert_creds, 79);
NM_TRAMP(security_inode_getsecctx, 80);
NM_TRAMP(security_inode_notifysecctx, 81);
NM_TRAMP(security_release_secctx, 82);
NM_TRAMP(set_nlink, 83);
NM_TRAMP(shrink_dcache_sb, 84);
NM_TRAMP(skb_trim, 85);
NM_TRAMP(sort, 86);
NM_TRAMP(static_key_disable, 87);
NM_TRAMP(static_key_enable, 88);
NM_TRAMP(synchronize_rcu, 89);
NM_TRAMP(truncate_inode_pages_final, 90);
NM_TRAMP(up_write, 91);
NM_TRAMP(vfs_getattr_nosec, 92);
NM_TRAMP(vfs_getxattr, 93);
NM_TRAMP(vfs_llseek, 94);
NM_TRAMP(vfs_setxattr, 95);
