/* SPDX-License-Identifier: GPL-2.0 */
/*
 * GENERATED by kpm/gen-shim.py -- do not edit by hand.
 *
 * Every kernel call in the engine becomes an indirect call through
 * nm_kpm_sym[]. See gen-shim.py for why a .kpm cannot call the kernel
 * directly, and why these signatures are read back out of the kernel
 * headers with typeof() instead of being written down.
 *
 * MUST be included AFTER the kernel headers -- a function-like macro for
 * memcpy expands inside string.h's declaration of memcpy otherwise.
 */
#ifndef _NM_KPM_SHIM_H
#define _NM_KPM_SHIM_H

#include "nm_kpm_syms.h"

/* KernelPatch does not come up on 6.12+ -- it hangs in its own pagetable
 * bring-up, so a module built for it could never load. Fail the compile
 * rather than ship something that bootloops. See kpm/README.md. */
#include <linux/version.h>
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0)
#error "KPM targets kernel 6.6 and older: KernelPatch does not boot on 6.12+."
#endif

/* Data objects: dereference the entry so &sym and sym[i] both still
 * denote the real kernel object. */
#define init_net (*(typeof(&init_net))nm_kpm_sym[NMS_init_net])
#define kmalloc_caches (*(typeof(&kmalloc_caches))nm_kpm_sym[NMS_kmalloc_caches])

/* Optional, may legitimately be NULL; the engine tests before calling. */
#define ghost_ctl ((typeof(&ghost_ctl))nm_kpm_sym[NMS_ghost_ctl])
#define ghost_get_rule ((typeof(&ghost_get_rule))nm_kpm_sym[NMS_ghost_get_rule])

/* Calls. typeof(&f) reads f's real prototype for this KMI: the
 * preprocessor does not re-expand f inside f's own expansion. */
#define __alloc_skb(...) ((typeof(&__alloc_skb))nm_kpm_sym[NMS___alloc_skb])(__VA_ARGS__)
#define __kmalloc(...) ((typeof(&__kmalloc))nm_kpm_sym[NMS___kmalloc])(__VA_ARGS__)
#define __netlink_dump_start(...) ((typeof(&__netlink_dump_start))nm_kpm_sym[NMS___netlink_dump_start])(__VA_ARGS__)
#define __netlink_kernel_create(...) ((typeof(&__netlink_kernel_create))nm_kpm_sym[NMS___netlink_kernel_create])(__VA_ARGS__)
#define __nla_parse(...) ((typeof(&__nla_parse))nm_kpm_sym[NMS___nla_parse])(__VA_ARGS__)
#define __nlmsg_put(...) ((typeof(&__nlmsg_put))nm_kpm_sym[NMS___nlmsg_put])(__VA_ARGS__)
#define __put_cred(...) ((typeof(&__put_cred))nm_kpm_sym[NMS___put_cred])(__VA_ARGS__)
#define __rcu_read_lock(...) ((typeof(&__rcu_read_lock))nm_kpm_sym[NMS___rcu_read_lock])(__VA_ARGS__)
#define __rcu_read_unlock(...) ((typeof(&__rcu_read_unlock))nm_kpm_sym[NMS___rcu_read_unlock])(__VA_ARGS__)
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 15, 0)
#define _printk(...) ((typeof(&_printk))nm_kpm_sym[NMS__printk])(__VA_ARGS__)
#endif
#define _raw_spin_lock(...) ((typeof(&_raw_spin_lock))nm_kpm_sym[NMS__raw_spin_lock])(__VA_ARGS__)
#define _raw_spin_unlock(...) ((typeof(&_raw_spin_unlock))nm_kpm_sym[NMS__raw_spin_unlock])(__VA_ARGS__)
#define call_rcu(...) ((typeof(&call_rcu))nm_kpm_sym[NMS_call_rcu])(__VA_ARGS__)
#define clear_inode(...) ((typeof(&clear_inode))nm_kpm_sym[NMS_clear_inode])(__VA_ARGS__)
#define d_add(...) ((typeof(&d_add))nm_kpm_sym[NMS_d_add])(__VA_ARGS__)
#define d_drop(...) ((typeof(&d_drop))nm_kpm_sym[NMS_d_drop])(__VA_ARGS__)
#define d_lookup(...) ((typeof(&d_lookup))nm_kpm_sym[NMS_d_lookup])(__VA_ARGS__)
#define d_splice_alias(...) ((typeof(&d_splice_alias))nm_kpm_sym[NMS_d_splice_alias])(__VA_ARGS__)
#define dentry_open(...) ((typeof(&dentry_open))nm_kpm_sym[NMS_dentry_open])(__VA_ARGS__)
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 15, 0)
#define do_trace_netlink_extack(...) ((typeof(&do_trace_netlink_extack))nm_kpm_sym[NMS_do_trace_netlink_extack])(__VA_ARGS__)
#endif
#define down_write(...) ((typeof(&down_write))nm_kpm_sym[NMS_down_write])(__VA_ARGS__)
#define dput(...) ((typeof(&dput))nm_kpm_sym[NMS_dput])(__VA_ARGS__)
#define fput(...) ((typeof(&fput))nm_kpm_sym[NMS_fput])(__VA_ARGS__)
#define free_inode_nonrcu(...) ((typeof(&free_inode_nonrcu))nm_kpm_sym[NMS_free_inode_nonrcu])(__VA_ARGS__)
#define full_name_hash(...) ((typeof(&full_name_hash))nm_kpm_sym[NMS_full_name_hash])(__VA_ARGS__)
#define generic_file_readonly_mmap(...) ((typeof(&generic_file_readonly_mmap))nm_kpm_sym[NMS_generic_file_readonly_mmap])(__VA_ARGS__)
#define generic_fillattr(...) ((typeof(&generic_fillattr))nm_kpm_sym[NMS_generic_fillattr])(__VA_ARGS__)
#define generic_permission(...) ((typeof(&generic_permission))nm_kpm_sym[NMS_generic_permission])(__VA_ARGS__)
#define idr_alloc(...) ((typeof(&idr_alloc))nm_kpm_sym[NMS_idr_alloc])(__VA_ARGS__)
#define idr_destroy(...) ((typeof(&idr_destroy))nm_kpm_sym[NMS_idr_destroy])(__VA_ARGS__)
#define idr_find(...) ((typeof(&idr_find))nm_kpm_sym[NMS_idr_find])(__VA_ARGS__)
#define idr_get_next(...) ((typeof(&idr_get_next))nm_kpm_sym[NMS_idr_get_next])(__VA_ARGS__)
#define idr_preload(...) ((typeof(&idr_preload))nm_kpm_sym[NMS_idr_preload])(__VA_ARGS__)
#define idr_remove(...) ((typeof(&idr_remove))nm_kpm_sym[NMS_idr_remove])(__VA_ARGS__)
#define igrab(...) ((typeof(&igrab))nm_kpm_sym[NMS_igrab])(__VA_ARGS__)
#define iput(...) ((typeof(&iput))nm_kpm_sym[NMS_iput])(__VA_ARGS__)
#define iterate_dir(...) ((typeof(&iterate_dir))nm_kpm_sym[NMS_iterate_dir])(__VA_ARGS__)
#define kasprintf(...) ((typeof(&kasprintf))nm_kpm_sym[NMS_kasprintf])(__VA_ARGS__)
#define kern_path(...) ((typeof(&kern_path))nm_kpm_sym[NMS_kern_path])(__VA_ARGS__)
#define kfree(...) ((typeof(&kfree))nm_kpm_sym[NMS_kfree])(__VA_ARGS__)
#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 10, 0)
#define kfree_call_rcu(...) ((typeof(&kfree_call_rcu))nm_kpm_sym[NMS_kfree_call_rcu])(__VA_ARGS__)
#endif
#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 0)
#define kfree_skb(...) ((typeof(&kfree_skb))nm_kpm_sym[NMS_kfree_skb])(__VA_ARGS__)
#endif
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0)
#define kfree_skb_reason(...) ((typeof(&kfree_skb_reason))nm_kpm_sym[NMS_kfree_skb_reason])(__VA_ARGS__)
#endif
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0)
#define kmalloc_large(...) ((typeof(&kmalloc_large))nm_kpm_sym[NMS_kmalloc_large])(__VA_ARGS__)
#endif
#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 0)
#define kmalloc_order(...) ((typeof(&kmalloc_order))nm_kpm_sym[NMS_kmalloc_order])(__VA_ARGS__)
#endif
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0)
#define kmalloc_trace(...) ((typeof(&kmalloc_trace))nm_kpm_sym[NMS_kmalloc_trace])(__VA_ARGS__)
#endif
#define kmem_cache_alloc(...) ((typeof(&kmem_cache_alloc))nm_kpm_sym[NMS_kmem_cache_alloc])(__VA_ARGS__)
#define kmem_cache_create(...) ((typeof(&kmem_cache_create))nm_kpm_sym[NMS_kmem_cache_create])(__VA_ARGS__)
#define kmem_cache_destroy(...) ((typeof(&kmem_cache_destroy))nm_kpm_sym[NMS_kmem_cache_destroy])(__VA_ARGS__)
#define kmem_cache_free(...) ((typeof(&kmem_cache_free))nm_kpm_sym[NMS_kmem_cache_free])(__VA_ARGS__)
#define kstrdup(...) ((typeof(&kstrdup))nm_kpm_sym[NMS_kstrdup])(__VA_ARGS__)
#define kstrndup(...) ((typeof(&kstrndup))nm_kpm_sym[NMS_kstrndup])(__VA_ARGS__)
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 10, 0)
#define kvfree_call_rcu(...) ((typeof(&kvfree_call_rcu))nm_kpm_sym[NMS_kvfree_call_rcu])(__VA_ARGS__)
#endif
#define lookup_one_len_unlocked(...) ((typeof(&lookup_one_len_unlocked))nm_kpm_sym[NMS_lookup_one_len_unlocked])(__VA_ARGS__)
#define mutex_lock(...) ((typeof(&mutex_lock))nm_kpm_sym[NMS_mutex_lock])(__VA_ARGS__)
#define mutex_unlock(...) ((typeof(&mutex_unlock))nm_kpm_sym[NMS_mutex_unlock])(__VA_ARGS__)
#define netlink_capable(...) ((typeof(&netlink_capable))nm_kpm_sym[NMS_netlink_capable])(__VA_ARGS__)
#define netlink_kernel_release(...) ((typeof(&netlink_kernel_release))nm_kpm_sym[NMS_netlink_kernel_release])(__VA_ARGS__)
#define netlink_rcv_skb(...) ((typeof(&netlink_rcv_skb))nm_kpm_sym[NMS_netlink_rcv_skb])(__VA_ARGS__)
#define netlink_unicast(...) ((typeof(&netlink_unicast))nm_kpm_sym[NMS_netlink_unicast])(__VA_ARGS__)
#define new_inode(...) ((typeof(&new_inode))nm_kpm_sym[NMS_new_inode])(__VA_ARGS__)
#define nla_put(...) ((typeof(&nla_put))nm_kpm_sym[NMS_nla_put])(__VA_ARGS__)
#define notify_change(...) ((typeof(&notify_change))nm_kpm_sym[NMS_notify_change])(__VA_ARGS__)
#define override_creds(...) ((typeof(&override_creds))nm_kpm_sym[NMS_override_creds])(__VA_ARGS__)
#define path_get(...) ((typeof(&path_get))nm_kpm_sym[NMS_path_get])(__VA_ARGS__)
#define path_put(...) ((typeof(&path_put))nm_kpm_sym[NMS_path_put])(__VA_ARGS__)
#define preempt_schedule(...) ((typeof(&preempt_schedule))nm_kpm_sym[NMS_preempt_schedule])(__VA_ARGS__)
#define prepare_creds(...) ((typeof(&prepare_creds))nm_kpm_sym[NMS_prepare_creds])(__VA_ARGS__)
#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
#define printk(...) ((typeof(&printk))nm_kpm_sym[NMS_printk])(__VA_ARGS__)
#endif
#define radix_tree_tagged(...) ((typeof(&radix_tree_tagged))nm_kpm_sym[NMS_radix_tree_tagged])(__VA_ARGS__)
#define rcu_barrier(...) ((typeof(&rcu_barrier))nm_kpm_sym[NMS_rcu_barrier])(__VA_ARGS__)
#define revert_creds(...) ((typeof(&revert_creds))nm_kpm_sym[NMS_revert_creds])(__VA_ARGS__)
#define security_inode_getsecctx(...) ((typeof(&security_inode_getsecctx))nm_kpm_sym[NMS_security_inode_getsecctx])(__VA_ARGS__)
#define security_inode_notifysecctx(...) ((typeof(&security_inode_notifysecctx))nm_kpm_sym[NMS_security_inode_notifysecctx])(__VA_ARGS__)
#define security_release_secctx(...) ((typeof(&security_release_secctx))nm_kpm_sym[NMS_security_release_secctx])(__VA_ARGS__)
#define set_nlink(...) ((typeof(&set_nlink))nm_kpm_sym[NMS_set_nlink])(__VA_ARGS__)
#define shrink_dcache_sb(...) ((typeof(&shrink_dcache_sb))nm_kpm_sym[NMS_shrink_dcache_sb])(__VA_ARGS__)
#define skb_trim(...) ((typeof(&skb_trim))nm_kpm_sym[NMS_skb_trim])(__VA_ARGS__)
#define sort(...) ((typeof(&sort))nm_kpm_sym[NMS_sort])(__VA_ARGS__)
#define static_key_disable(...) ((typeof(&static_key_disable))nm_kpm_sym[NMS_static_key_disable])(__VA_ARGS__)
#define static_key_enable(...) ((typeof(&static_key_enable))nm_kpm_sym[NMS_static_key_enable])(__VA_ARGS__)
#define synchronize_rcu(...) ((typeof(&synchronize_rcu))nm_kpm_sym[NMS_synchronize_rcu])(__VA_ARGS__)
#define truncate_inode_pages_final(...) ((typeof(&truncate_inode_pages_final))nm_kpm_sym[NMS_truncate_inode_pages_final])(__VA_ARGS__)
#define up_write(...) ((typeof(&up_write))nm_kpm_sym[NMS_up_write])(__VA_ARGS__)
#define vfs_getattr_nosec(...) ((typeof(&vfs_getattr_nosec))nm_kpm_sym[NMS_vfs_getattr_nosec])(__VA_ARGS__)
#define vfs_getxattr(...) ((typeof(&vfs_getxattr))nm_kpm_sym[NMS_vfs_getxattr])(__VA_ARGS__)
#define vfs_llseek(...) ((typeof(&vfs_llseek))nm_kpm_sym[NMS_vfs_llseek])(__VA_ARGS__)
#define vfs_setxattr(...) ((typeof(&vfs_setxattr))nm_kpm_sym[NMS_vfs_setxattr])(__VA_ARGS__)

#endif /* _NM_KPM_SHIM_H */
