/* SPDX-License-Identifier: GPL-2.0 */
/*
 * GENERATED by kpm/gen-shim.py -- do not edit by hand.
 *
 * The small residue that trampolines cannot cover: data taken by address,
 * the slab inlines, and the weak optional pair. Everything callable is
 * handled by nm_kpm_tramp.c instead.
 *
 * Include AFTER the kernel headers. A function-like macro named after a
 * kernel function expands inside that function's own declaration too.
 */
#ifndef _NM_KPM_SHIM_H
#define _NM_KPM_SHIM_H

#include "nm_kpm_syms.h"

/* KernelPatch does not come up on 6.12+ -- it hangs in its own pagetable
 * bring-up, so a module built for it could never load. Fail the compile
 * rather than ship something that bootloops. See kpm/README.md. */
#include <linux/version.h>
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0)
#error "KPM targets kernel 6.6 and older: KernelPatch does not boot on 6.12+."
#endif

/* Data taken by address in the engine's own text. */
#define init_net (*(typeof(&init_net))nm_kpm_sym[NMS_init_net])

/*
 * The slab entry points are static inlines that index the kmalloc_caches
 * ARRAY, which no trampoline can stand in for. Redirecting them to
 * __kmalloc -- which does have one -- stops those inlines being
 * instantiated, and takes kmalloc_caches, kmalloc_trace and kmalloc_large
 * out of the undefined set along with them.
 */
#undef kmalloc
#undef kzalloc
#undef kmalloc_array
#define kmalloc(sz, fl)		__kmalloc((sz), (fl))
#define kzalloc(sz, fl)		__kmalloc((sz), (fl) | __GFP_ZERO)
#define kmalloc_array(n, sz, fl)	__kmalloc((n) * (sz), (fl))

/*
 * Optional, and legitimately NULL: the engine tests the address before
 * calling and that test is a real feature probe, so a trampoline would be
 * non-NULL and falsely advertise ghost support.
 *
 * They expand to a POINTER rather than a lookup because the engine DECLARES
 * them as well as calling them:
 *
 *     extern int ghost_ctl(const char *, size_t) __attribute__((weak));
 *
 * and a macro whose name is followed by "(" expands inside that declaration
 * too. (*nm_w_ghost_ctl) leaves it well-formed -- it becomes a weak function
 * POINTER -- while calls and the !ghost_ctl test both still mean what the
 * engine intended. nm_engine.c defines them and binds them at init.
 */
#define ghost_ctl (*nm_w_ghost_ctl)
#define ghost_get_rule (*nm_w_ghost_get_rule)

#endif /* _NM_KPM_SHIM_H */
